african_capitals = {
    'Algeria': 'Algiers',
    'Angola': 'Luanda',
    'Benin': 'Porto-Novo',
    'Botswana': 'Gaborone',
    'Burkina faso': 'Ouagadougou',
    'Burundi': 'Gitega',
    'Cabo Verde': 'Praia',
    'Cameroon': 'Yaoundé',
    'Central African Republic': 'Bangui',
    'Chad': "N'Djamena",
    'Comoros': 'Moroni',
    'Democratic Republic of the Congo': 'Kinshasa',
    'Republic of the Congo': 'Brazzaville',
    'Djibouti': 'Djibouti',
    'Egypt': 'Cairo',
    'Equatorial Guinea': 'Malabo',
    'Eritrea': 'Asmara',
    'Eswatini': 'Mbabane' or 'Lobamba',
    'Ethiopia': 'Addis Ababa',
    'Gabon': 'Libreville',
    'Gambia': 'Banjul',
    'Ghana': 'Accra',
    'Guinea': 'Conakry',
    'Guinea Bissau': 'Bissau',
    'Ivory coast': 'Yamoussoukro' or 'Abidjan',
    'Kenya': 'Nairobi',
    'Lesotho': 'Maseru',
    'Liberia': 'Monrovia',
    'Libya': 'Tripoli',
    'Madagascar': 'Antananarivo',
    'Malawi': 'Lilongwe',
    'Mali': 'Bemako',
    'Mauritania': 'Nouakchott',
    'Mauritius': 'Port Louis',
    'Morocco': 'Rabat',
    'Mozambique': 'Maputo',
    'Namibia': 'Windhoek',
    'Niger': 'Niamey',
    'Nigeria': 'Abuja',
    'Rwanda': 'Kigali',
    'Sao Tome and Principe': 'Sao Tome',
    'Senegal': 'Dakar',
    'Seychelles': 'Victoria',
    'Sierra Leone': 'Freetown',
    'Somalia': 'Mogadishu',
    'South Africa': 'Pretoria' or 'Cape town' or 'Bloemfontein',
    'South Sudan': 'Juba',
    'Sudan': 'Khartoum',
    'Tanzania': 'Dodoma',
    'Togo': 'Lomé',
    'Tunisia': 'Tunis',
    'Uganda': 'Kampala',
    'Zambia': 'Lusaka',
    'Zimbabwe': 'Harare'
}