europe_capitals = {
    "albania": "tirana",
    "andorra": "andorra la vella",
    "austria": "vienna",
    "belarus": "minsk",
    "belgium": "brussels",
    "bosnia and herzegovina": "sarajevo",
    "bulgaria": "sofia",
    "croatia": "zagreb",
    "cyprus": "nicosia",
    "czech republic": "prague",
    "denmark": "copenhagen",
    "estonia": "tallinn",
    "finland": "helsinki",
    "france": "paris",
    "georgia": "tbilisi",
    "germany": "berlin",
    "greece": "athens",
    "hungary": "budapest",
    "iceland": "reykjavik",
    "ireland": "dublin",
    "italy": "rome",
    "kosovo": "pristina",
    "latvia": "riga",
    "liechtenstein": "vaduz",
    "lithuania": "vilnius",
    "luxembourg": "luxembourg",
    "malta": "valletta",
    "moldova": "chisinau",
    "monaco": "monaco",
    "montenegro": "podgorica",
    "netherlands": "amsterdam",
    "north macedonia": "skopje",
    "norway": "oslo",
    "poland": "warsaw",
    "portugal": "lisbon",
    "romania": "bucharest",
    "russia": "moscow",
    "san marino": "san marino",
    "serbia": "belgrade",
    "slovakia": "bratislava",
    "slovenia": "ljubljana",
    "spain": "madrid",
    "sweden": "stockholm",
    "switzerland": "bern",
    "turkey": "ankara",
    "ukraine": "kyiv",
    "united kingdom": "london",
    "vatican city": "vatican city"}
