asia_capitals = {
    "afghanistan": "kabul",
    "armenia": "yerevan",
    "azerbaijan": "baku",
    "bahrain": "manama",
    "bangladesh": "dhaka",
    "bhutan": "thimphu",
    "brunei": "bandar seri begawan",
    "cambodia": "phnom penh",
    "china": "beijing",
    "cyprus": "nicosia",
    "georgia": "tbilisi",
    "india": "new delhi",
    "indonesia": "jakarta",
    "iran": "tehran",
    "iraq": "baghdad",
    "israel": "jerusalem",
    "japan": "tokyo",
    "jordan": "amman",
    "kazakhstan": "astana",
    "kuwait": "kuwait city",
    "kyrgyzstan": "bishkek",
    "laos": "vientiane",
    "lebanon": "beirut",
    "malaysia": "kuala lumpur",
    "maldives": "malé",
    "mongolia": "ulaanbaatar",
    "myanmar": "naypyidaw",
    "nepal": "kathmandu",
    "north korea": "pyongyang",
    "oman": "muscat",
    "pakistan": "islamabad",
    "palestine": "ramallah",
    "philippines": "manila",
    "qatar": "doha",
    "russia": "moscow",
    "saudi arabia": "riyadh",
    "singapore": "singapore",
    "south korea": "seoul",
    "sri lanka": "sri jayawardenepura kotte",
    "syria": "damascus",
    "taiwan": "taipei",
    "tajikistan": "dushanbe",
    "thailand": "bangkok",
    "timor-leste": "dili",
    "turkey": "ankara",
    "turkmenistan": "ashgabat",
    "united arab emirates": "abu dhabi",
    "uzbekistan": "tashkent",
    "vietnam": "hanoi",
    "yemen": "sana'a"
}